// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/26/2025, 8:50:49 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/vboxuser/epitech/portfolio/gitport/raul59209portfolio/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vboxuser/epitech/portfolio/gitport/raul59209portfolio/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vboxuser/epitech/portfolio/gitport/raul59209portfolio/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vboxuser/epitech/portfolio/gitport/raul59209portfolio/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vboxuser/epitech/portfolio/gitport/raul59209portfolio/app/plugins/**/*.{js,ts,mjs}","/home/vboxuser/epitech/portfolio/gitport/raul59209portfolio/app/composables/**/*.{js,ts,mjs}","/home/vboxuser/epitech/portfolio/gitport/raul59209portfolio/app/utils/**/*.{js,ts,mjs}","/home/vboxuser/epitech/portfolio/gitport/raul59209portfolio/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vboxuser/epitech/portfolio/gitport/raul59209portfolio/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/vboxuser/epitech/portfolio/gitport/raul59209portfolio/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/vboxuser/epitech/portfolio/gitport/raul59209portfolio/app/app.config.{js,ts,mjs}","/home/vboxuser/epitech/portfolio/gitport/raul59209portfolio/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;